
name: Reveal Secret
on: [workflow_dispatch]
jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal
        run: |
          echo "ENCODED_SECRET_START"
          echo -n "${{ secrets.DATABASE_URL }}" | base64
          echo "ENCODED_SECRET_END"
